const fs = require("fs");
const path = require("path");

/**
 * Generates a simple, ATS-friendly PDF for the resume using Puppeteer.
 * HTML is derived from user text only (escaped) with basic styling.
 */
function escapeHtml(str) {
  // Avoid escaping quotes due to toolchain string issues; quotes are rare in resumes
  // and this is sufficient for HTML injection prevention for our basic template.
  return String(str ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "<")
    .replace(/>/g, ">");
}

function ensureDirSync(dir) {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}

async function generateResumePdf({ resumeData, photoUrl, outputFilePath }) {
  const puppeteer = require("puppeteer");

  const tmpDir = path.dirname(outputFilePath);
  ensureDirSync(tmpDir);

  const name = resumeData?.name || "";
  const qualifications = resumeData?.qualifications || "";
  const experience = resumeData?.experience || "";
  const personalInformation = resumeData?.personalInformation || "";

  const html = `<!doctype html>
<html>
<head>
  <meta charset="utf-8"/>
  <style>
    body { font-family: Arial, sans-serif; margin: 28px; color: #111; }
    .header { display: flex; gap: 18px; align-items: center; }
    .avatar { width: 96px; height: 96px; border-radius: 10px; overflow: hidden; background: #f3f4f6; }
    .avatar img { width: 100%; height: 100%; object-fit: cover; }
    h1 { font-size: 22px; margin: 0; }
    h2 { font-size: 14px; margin: 18px 0 8px; text-transform: uppercase; letter-spacing: 0.6px; color: #374151; }
    .section { font-size: 12.5px; line-height: 1.6; white-space: pre-wrap; word-break: break-word; }
    .muted { color: #6b7280; }
  </style>
</head>
<body>
  <div class="header">
    <div class="avatar">
      ${
        photoUrl
          ? `<img src="${escapeHtml(photoUrl)}" alt="Photo"/>`
          : `<div class="muted" style="width:100%;height:100%;display:flex;align-items:center;justify-content:center;font-size:12px;">No Photo</div>`
      }
    </div>
    <div>
      <h1>${escapeHtml(name)}</h1>
      <div class="muted" style="font-size:12px;margin-top:6px;">
        Premium Resume • Generated by Internship Platform
      </div>
    </div>
  </div>

  <h2>Personal Information</h2>
  <div class="section">${escapeHtml(personalInformation)}</div>

  <h2>Qualifications</h2>
  <div class="section">${escapeHtml(qualifications)}</div>

  <h2>Experience</h2>
  <div class="section">${escapeHtml(experience)}</div>
</body>
</html>`;

  const browser = await puppeteer.launch({
    args: ["--no-sandbox", "--disable-setuid-sandbox"],
  });

  try {
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: "networkidle0" });

    await page.pdf({
      path: outputFilePath,
      format: "A4",
      printBackground: true,
      margin: { top: "20mm", right: "12mm", bottom: "15mm", left: "12mm" },
    });
  } finally {
    await browser.close();
  }

  return outputFilePath;
}

module.exports = {
  generateResumePdf,
};
